# ArgoCD Application for Tempo (Distributed Tracing)
# Uses official Grafana Helm chart
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: tracing
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Disable auto-sync - enable manually when tracing is needed
  annotations:
    argocd.argoproj.io/sync-options: "Prune=false"
spec:
  project: default

  source:
    # Official Grafana Helm Chart Repository
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "1.7.1"  # Pin to specific version

    helm:
      releaseName: tempo
      values: |
        # Tempo Configuration
        tempo:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

          # Trace storage configuration
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal

          # Retention settings
          retention: 48h

          # Receivers configuration
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            zipkin:
              endpoint: 0.0.0.0:9411
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_http:
                  endpoint: 0.0.0.0:14268

        # Persistence
        persistence:
          enabled: true
          size: 10Gi

        # Service for trace ingestion
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  # Manual sync - tracing is optional
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
