# Falco Runtime Security
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  labels:
    app: falco
    component: security
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 4.0.0
    helm:
      releaseName: falco
      values: |
        driver:
          kind: ebpf
        
        falco:
          jsonOutput: true
          jsonIncludeOutputProperty: true
          httpOutput:
            enabled: true
            url: "http://falcosidekick:2801"
          
          rules:
            - macro: container
              condition: container.id != host
            
            # Custom rules
            - rule: Terminal shell in container
              desc: A shell was spawned in a container
              condition: >
                spawned_process and container
                and shell_procs
                and not known_shell_spawn_binaries
              output: >
                Shell spawned in container
                (user=%user.name container_id=%container.id
                container_name=%container.name shell=%proc.name
                parent=%proc.pname cmdline=%proc.cmdline)
              priority: WARNING
        
        falcosidekick:
          enabled: true
          webui:
            enabled: true
          config:
            slack:
              webhookurl: ""  # Configure via secret
  destination:
    server: https://kubernetes.default.svc
    namespace: falco-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
